project_name: certissuer
release:
  github:
    owner: julian7
    name: certissuer
builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  main: ./cmd/certissuer
  ldflags:
  - -s -w -X main.version={{.Version}}
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
archives:
- name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
  replacements:
    darwin: macos
  format: binary
  files:
  - none*
checksum:
  name_template: 'SHA256SUMS.{{.ProjectName}}-{{.Version}}'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
